services:
  - type: web
    name: signara-ml-api
    runtime: python
    rootDir: sign_ai
    buildCommand: pip install -r requirements_api.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: starter
