services:
  - type: web
    name: signara-test
    runtime: python
    rootDir: src/sign-translate
    buildCommand: pip install -r requirements_api.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
